name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  osx:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          npm install -g bats
      - name: Build
        run: |
          ./build.sh ha_lineairdb_storage_engine.so
      - name: Copy into MySQL plugin directory
        run: |
          cp build/plugin_output_directory/ha_lineairdb_storage_engine.so $(echo "SHOW VARIABLES LIKE 'plugin_dir';" | mysql -uroot -proot -N | awk '{print $2}')
      - name: Setup MySQL Server
        run: |
          echo "INSTALL PLUGIN lineairdb SONAME 'ha_lineairdb_storage_engine.so'" | mysql -uroot -proot
      - name: Exec test scripts
        run: |
          bats tests/CI.bats
