name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          npm install -g bats
          brew install boost ninja
      - name: Build
        run: |
          ./build.sh
      - name: Setup MySQL Server
        run: |
          rm -rf base
          mkdir -p base/data
          build/bin/mysqld --defaults-file=./.github/my.cnf --initialize-insecure
          build/bin/mysqld --defaults-file=./.github/my.cnf --daemonize
          echo "INSTALL PLUGIN lineairdb SONAME 'ha_lineairdb_storage_engine.so'" | build/bin/mysql -u root
          echo show engines | build/bin/mysql -u root
      - name: execute testing
        run: bats tests/CI.bats
